name: Deploy

on:
  push:
    branches:
      - main
jobs: 
     build: 
      runs-on: ubuntu-latest
      steps: 
       - uses: actions/checkout@v2
       - uses: akhileshns/herokudeploy@v3.12.12
         with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sistemamitte"
          heroku_email: "jacigarcia3@gmail.com"